services:
  - type: web
    name: deepfake-detection-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd server && gunicorn server.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: server.settings
    plan: free
    autoDeploy: false
    disk:
      name: deepfake-data
      mountPath: /data
      sizeGB: 1
    healthCheckPath: /api/health/
    apt:
      packages:
        - cmake
        - libgl1-mesa-glx